### ISSUE TITLE
request of TLSA record fails on a new context for some nameservers unless A record requested first

### ISSUE THREAD

**Issue by simsong** [getdnsapi/getdns-python-bindings#28] opened 2015-06-17 15:28 UTC
For reasons that I do not understand, attempting to fetch a TLSA record on the host `_443._tcp.001.tlsa.good.test.had-pilot.biz` fails unless an A record is requested first.

That is, this code fails with a timeout and returns a NoneType:

```
import getdns
extensions = {"dnssec_return_validation_chain" : getdns.EXTENSION_TRUE}
ctx = getdns.Context()

hostname = "_443._tcp.001.tlsa.good.test.had-pilot.biz"
results = ctx.general(name=hostname,request_type=getdns.RRTYPE_TLSA,extensions=extensions)
print(results)
```

But this code works fine:

```
import getdns
extensions = {"dnssec_return_validation_chain" : getdns.EXTENSION_TRUE}
ctx = getdns.Context()

hostname = "_443._tcp.001.tlsa.good.test.had-pilot.biz"
results = ctx.general(name=hostname,request_type=getdns.RRTYPE_A,extensions=extensions)
results = ctx.general(name=hostname,request_type=getdns.RRTYPE_TLSA,extensions=extensions)
print(results)
```

**Comment by MelindaShore** [comment] 2015-06-17 15:49
This was reported on a mailing list yesterday but we're having problems duplicating the behavior.  I can't get an A record for this hostname at all, while another project member never has it fail.  Running dig on this domain name from my machine also returns 0 records.  It appears to be a server-related problem but we'll leave the ticket open until we can confirm that that's the case.

There's further information available here:  https://getdnsapi.net/pipermail/users/2015-June/000054.html .

**Comment by simsong** [comment] 2015-06-17 15:55
Thanks. I'm not on the mailing list. In any event, it's probably better to track here.

I upgraded to getdns 0.2.0 but the problem persisted.

I suppose that it's 'possible' that this is a server problem, but I would expect better error reporting from the API in that case.

**Comment by MelindaShore** [comment] 2015-06-17 16:55
This is expected behavior when no records are returned.  If the query is correctly formed the api returns successfully.  If all you're interested in is the addresses, you can look at Result().just_address_answers - if no A or AAAA record is returned it will have length 0.

**Comment by simsong** [comment] 2015-06-17 19:05
Yes, but there is a TLSA record. It reliably comes when an A Request is done on the same context first, and not if the TLSA query is done first. Is that proper?

**Comment by simsong** [comment] 2015-06-17 20:24
Hi, @MelindaShore , I didn't fully appreciate your previous comment about different users getting different responses from the DNS servers.  There is no A record for the hostname, there is only a TLSA record. However, my experience is that the getdnsapi will only return the TLSA record if I first request the A record on the same context. I was not aware that the context maintains this kind of state. Why would a TLSA query succeed only after a failed A query?

**Comment by MelindaShore** [comment] 2015-06-17 23:00
On 6/17/15 12:24 PM, Simson L. Garfinkel wrote:
> Hi, @MelindaShore <https://github.com/MelindaShore> , I didn't fully
> appreciate your previous comment about different users getting different
> responses from the DNS servers. There is no A record for the hostname,
> there is only a TLSA record. However, my experience is that the
> getdnsapi will only return the TLSA record if I first request the A
> record on the same context. I was not aware that the context maintains
> this kind of state. Why would a TLSA query succeed only after a failed A
> query?

Don't know - so far I'm unable to replicate this.  Once I can,
or somebody else can, the first thing we'll do is isolate whether
this is happening in the bindings or libgetdns.  My suspicion is
that if there is a problem it's likely in libgetdns, since the
bindings are really wrappers around libgetdns functions, doing
conversions between getdns and Python data structures without
looking inside them (with a few exceptions), and interfacing
to the Python interpreter.  I'll take another look at it this
evening.

Melinda


-- 
Melinda Shore
No Mountain Software
melinda.shore@nomountain.net

"Software longa, hardware brevis."

**Comment by wtoorop** [comment] 2015-06-18 13:19
Hi Simon,

I sometimes have your error, and sometimes not :)

willem@bonobo:~/sink/nist$ ./without_a.py
hostname= _443._tcp.301ss.tlsa.good.test.had-pilot.biz request_type= 52
extensions= {'dnssec_return_validation_chain': 1000}

willem@bonobo:~/sink/nist$ ./without_a.py
hostname= _443._tcp.301ss.tlsa.good.test.had-pilot.biz request_type= 52
extensions= {'dnssec_return_validation_chain': 1000}
{'ttl': 600, 'rdata': {'rdata_raw': <read-only buffer ptr 0x2344920,
size 35 at 0x7effdea70070>, 'certificate_usage': 3,
'certificate_association_data': <read-only buffer ptr 0x23449f0, size 32
at 0x7effdea70030>, 'matching_type': 1, 'selector': 0}, 'type': 52,
'class': 1, 'name': '_443._tcp.301ss.tlsa.good.test.had-pilot.biz.'}

Your name servers are very broken though!

They give different answers every time.  This is likely causing the
problem.  For example notice the inconsistency whether
ns1.had-pilot.biz. does or does not exist, plus the different SOA
numbers in the two queries below:

willem@bonobo:~/repos/getdns/src$ dig @129.6.100.201 had-pilot.biz. soa
+dnssec +cd

; <<>> DiG 9.10.2rc2 <<>> @129.6.100.201 had-pilot.biz. soa +dnssec +cd
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29540
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 3, ADDITIONAL: 5
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 3072
;; QUESTION SECTION:
;had-pilot.biz.			IN	SOA

;; ANSWER SECTION:
had-pilot.biz.		3600	IN	SOA	ns2.had-pilot.biz. no-reply.had-pilot.biz.
20111556 43200 43200 1209600 600
had-pilot.biz.		3600	IN	RRSIG	SOA 8 2 3600 20150625030023 20150618020023
24186 had-pilot.biz.
bN57c7bfeK+XfxcN5FcRVot404oEOq3kb/3b6bY2/Zh7RiNmfNtWiqrZ
tZ6gGnJqf0wUrjyYtN2u4v3mLLVGjYPmrSH01WqVVuQ+oXNicvQMCDrd
2PZMxjrj2W4jkYmGw2PHoB1T/VhaKBKvSsPlWBUvql6ZB8q3rmC7WNtr L/w=

;; AUTHORITY SECTION:
had-pilot.biz.		3600	IN	NS	ns1.had-pilot.biz.
had-pilot.biz.		3600	IN	NS	ns2.had-pilot.biz.
had-pilot.biz.		3600	IN	RRSIG	NS 8 2 3600 20150625030023 20150618020023
24186 had-pilot.biz.
bprJ1BOrEmtftlhWaplvQsVbv3gpBXX1/US8cPXImFNNMJSeHeOuz8VE
Ms/z6GxUqO/v9lz5kNPItgOlfz8ti4MlllpKEkaNUSCkN1am7h3qI3Sg
AfvtMMEu0zpq80p5zf7/Oxucsttrq2QmEHgiXj7C3BdiRyeFdwuEQ0gn LOk=

;; ADDITIONAL SECTION:
ns1.had-pilot.biz.	3600	IN	A	129.6.100.200
ns1.had-pilot.biz.	3600	IN	RRSIG	A 8 3 3600 20150625030023
20150618020023 24186 had-pilot.biz.
JXOX8kbnBSwVTeGw41hjUrRXuf/m5EIlfyiCEZEAp56xA8YTRzqZR2mo
aqO/PiIXyuedrQqUIzR5/yRsx35bSkG3ubi3ShabsyFGVsoNp6q3uonH
FzHmIdyJyVrJtei/KlzUB7DObxqX4vxy1vcsoEL2jA3DBQpoSZGkbvdm iWE=
ns2.had-pilot.biz.	3600	IN	A	129.6.100.201
ns2.had-pilot.biz.	3600	IN	RRSIG	A 8 3 3600 20150625030023
20150618020023 24186 had-pilot.biz.
jqjrmN8Oq9p/7oeWlQ5W3IMaHDndcOoB8PSDMRT1qVAoMfp0fZcLZsH0
gMe0EHXBp5HA6ycpiUH/su4u6lQAqsE5Wmch6AfbHfkg21b7hRCy3+6I
G+Xtpgtx+t9XUw8hdsgwK3XohsqlLd/4MI3kGn6R3MFdRuiFgk3E9Ds3 qbo=

;; Query time: 335 msec
;; SERVER: 129.6.100.201#53(129.6.100.201)
;; WHEN: Thu Jun 18 15:15:59 CEST 2015
;; MSG SIZE  rcvd: 847



willem@bonobo:~$ dig @129.6.100.201 ns1.had-pilot.com. a +dnssec +cd

; <<>> DiG 9.10.2rc2 <<>> @129.6.100.201 ns1.had-pilot.com. a +dnssec +cd
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 40502
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 6, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 3072
;; QUESTION SECTION:
;ns1.had-pilot.com.		IN	A

;; AUTHORITY SECTION:
had5.had-pilot.com.	3600	IN	NSEC	ns2.had-pilot.com. A RRSIG NSEC
had5.had-pilot.com.	3600	IN	RRSIG	NSEC 8 3 3600 20150625030024
20150618020024 28335 had-pilot.com.
bHX8Y2Y8nr3p+kuHBTe9FIBebbXIoZhGCJIKGvQCYpojKNFY4fE4drgb
3+M5Vn0RF2xRpPBA4oackMiljSivnUH1WeFpnyJZkwtB3mBqiwN7swZV
3KsEWYtdwiY8FdfG4tEVlTkvHpxJzaC9PcvuxAoE2H2ACYXwYpF/i2uC GhI=
had-pilot.com.		3600	IN	NSEC	had1.had-pilot.com. NS SOA MX TXT RRSIG
NSEC DNSKEY SPF
had-pilot.com.		3600	IN	RRSIG	NSEC 8 2 3600 20150625030024
20150618020024 28335 had-pilot.com.
HV6/69+uNEUc3AJuhR/j1s/5pXHAPmwIzdygrubTGwowUCWAzNJYdq5c
t8jfMp0U2jEhfX3lEPaPiM1GbgC8GW0A5zHcUdl7AatiTpQGWWHVPzL+
L/+YIUMPodGkGNWV24jajN0zRRfsP4lQZbiE+y2cAgeWbU+7kFEfdKtb CME=
had-pilot.com.		3600	IN	SOA	ns2.had-pilot.com. scottr.nist.gov. 20131045
43200 43200 1209600 3600
had-pilot.com.		3600	IN	RRSIG	SOA 8 2 3600 20150625030024 20150618020024
28335 had-pilot.com.
DpQUH88je0FfSFFF0Mf4W9YBAvLBKAqn6hZ5c9GSH/ONDQzbmcUUXms4
rSZ9+J24fk8IpI3mNEQ0ItUZBMCw39oi6f1rq/4WRpOoAv9XpuDPg0d3
oSWw5fME2MDmCIYiC/B1wUC+w59f97NaZ1eIaZNMkjqKMzm7xWJOgvcD 1Xk=

;; Query time: 93 msec
;; SERVER: 129.6.100.201#53(129.6.100.201)
;; WHEN: Thu Jun 18 13:58:02 CEST 2015
;; MSG SIZE  rcvd: 711


You know, there is only so much server failure one can detect from a
library...

Op 18-06-15 om 01:00 schreef Melinda Shore:

**Comment by simsong** [comment] 2015-06-18 13:54
Thanks. That certainly does seem odd.

**Comment by MelindaShore** [comment] 2017-07-15 11:35
I'm still unable to replicate the problem but dig is now returning consistent results for this query, so I'm closing this.  Please reopen if you're still seeing the issue.

**Closed by MelindaShore** 2017-07-15 11:35 UTC

**Comment by simsong** [comment] 2017-07-15 11:44
Okay. Thanks.

(Sent from my laptop.)

__________________________
Simson L. Garfinkel
https://simson.net/
202-649-0029
